import { mobiscroll } from '../src/js/modules/mobiscroll.angular';
export * from '../src/js/modules/mobiscroll.angular';
import '../src/js/themes/ios';
import '../src/js/themes/mobiscroll-dark';
import '../src/js/themes/material';
import '../src/js/themes/ghours';
import '../src/js/themes/ghoursios';
import '../src/js/themes/ghoursmaterial';
import '../src/js/themes/auto-theme';
export default mobiscroll;
